// GENERATED by scripts/sync-shared.js from src/lib/time/zoned.ts. Edit the source, then re-run the script.
/**
 * Wall-clock time in a given IANA time zone, as a "floating" Date.
 *
 * The recurrence engine works with local-time Dates (`new Date(y, m, d, h, min)`). On a
 * phone, "local" is the user's zone. On a server it is UTC, so to reuse the engine there
 * we rebuild each instant as the same wall-clock reading in the runtime's local time:
 * 07:30 in Bogotá becomes a Date that reads 07:30 locally, whatever the server zone.
 * Floating dates are only meaningful against other floating dates from the same runtime.
 */

const formatters = new Map<string, Intl.DateTimeFormat>();

function formatterFor(timeZone: string): Intl.DateTimeFormat {
  let formatter = formatters.get(timeZone);
  if (!formatter) {
    formatter = new Intl.DateTimeFormat('en-US', {
      timeZone,
      hourCycle: 'h23',
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });
    formatters.set(timeZone, formatter);
  }
  return formatter;
}

/** True when the runtime knows the zone (an unknown one would throw). */
export function isValidTimeZone(timeZone: string): boolean {
  try {
    formatterFor(timeZone);
    return true;
  } catch {
    return false;
  }
}

/** The wall-clock reading of `instant` in `timeZone`, as a floating Date. Unknown zones read as UTC. */
export function toZonedFloating(instant: Date, timeZone: string): Date {
  const zone = isValidTimeZone(timeZone) ? timeZone : 'UTC';
  const parts = Object.fromEntries(
    formatterFor(zone)
      .formatToParts(instant)
      .filter((p) => p.type !== 'literal')
      .map((p) => [p.type, Number(p.value)]),
  ) as Record<'year' | 'month' | 'day' | 'hour' | 'minute' | 'second', number>;
  return new Date(parts.year, parts.month - 1, parts.day, parts.hour, parts.minute, parts.second);
}
