// Copies the app's pure TypeScript modules into supabase/functions/_shared/ so the Edge
// Functions (Deno) run the exact same logic. Deno needs explicit `.ts` import paths and
// knows nothing about the `@/` alias, so imports are rewritten on the way.
// Run: `node scripts/sync-shared.js`. A test fails when the copies drift.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

const FILES = [
  { from: 'src/lib/recurrence/index.ts', to: 'supabase/functions/_shared/recurrence.ts' },
  { from: 'src/lib/time/zoned.ts', to: 'supabase/functions/_shared/zoned.ts' },
  { from: 'src/features/coach/weekly-summary.ts', to: 'supabase/functions/_shared/weekly-summary.ts' },
];

const IMPORTS = {
  '@/lib/recurrence': './recurrence.ts',
  '@/lib/time/zoned': './zoned.ts',
};

function transform(source, from) {
  let out = source;
  for (const [alias, target] of Object.entries(IMPORTS)) out = out.split(`'${alias}'`).join(`'${target}'`);
  return `// GENERATED by scripts/sync-shared.js from ${from}. Edit the source, then re-run the script.\n${out}`;
}

function expected() {
  return FILES.map(({ from, to }) => ({
    to,
    content: transform(fs.readFileSync(path.join(root, from), 'utf8'), from),
  }));
}

if (require.main === module) {
  for (const { to, content } of expected()) {
    fs.mkdirSync(path.dirname(path.join(root, to)), { recursive: true });
    fs.writeFileSync(path.join(root, to), content);
    console.log(`synced ${to}`);
  }
}

/** Paths whose committed copy differs from what the script would write. */
function stale() {
  return expected()
    .filter(({ to, content }) => !fs.existsSync(path.join(root, to)) || fs.readFileSync(path.join(root, to), 'utf8') !== content)
    .map(({ to }) => to);
}

module.exports = { stale };
